### ISSUE TITLE
Stray Dockerfile causes errors

### ISSUE THREAD

**Issue by taylorrice** [noop-cloud/noop-local#2]
If there is an unused Dockerfile in the project, it can cause an error even though it has no effect on running the app. Deleting the Dockerfile resolved the issue. Issue can be seen in commit a1a0703

**Comment by mwkaufman** [comment]
Ran into this issue, is there a use case for mixing Dockerfiles and Noopfiles? I think I'd like noop-local to ignore Dockerfiles in a project.

**Comment by rahulsen** [comment]
This bug prevents Noopfile changes from taking effect. Even after quitting and doing a fresh `noop run` . It is sure to frustrate any new developer for sure.

**Comment by derekwolpert** [comment]
@mwkaufman @rahulsen Resolved in https://github.com/noop-cloud/noop-local/pull/53
