### ISSUE TITLE
predeploy tasks shouldn't run before postgres resource healthy

### ISSUE THREAD

**Issue by mwkaufman** [noop-cloud/noop-local#23]
Currently noop-local will docker run postgres and then proceed to run the predeploy tasks. Even though the postgres container is running, the postgres process may not be ready to serve connections which can cause the predeploy task to fail if it say needs to run a rake db:setup.

`% docker logs b01cb7951ae7
rake aborted!
PG::ConnectionBad: FATAL:  the database system is starting up`

Not a blocker, just added a "sleep 15" to my db migrate script.

**Comment by mwkaufman** [comment]
One option is we could create noop resource images with healthchecks added over the generic image.

**Comment by derekwolpert** [comment]
Resolved in https://github.com/noop-cloud/noop-local/pull/53
