### ISSUE TITLE
Task names don't make sense

### ISSUE THREAD

**Issue by mwkaufman** [noop-cloud/noop-local#40]
Predeploy and postdeploy don't make sense as steps in the middle of a deploy:

See AWS CodeDeploy's lifecycle event hooks:
https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html

Kubernetes has a concept of init containers:
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Comment by mwkaufman** [comment]
I propose preservices and postservices.

**Comment by arbitrarytech** [comment]
I'm leaning towards `BeforeServices` and `BeforeTraffic`.

**Comment by mwkaufman** [comment]
Maybe more descriptive:
e.g. beforeLaunchServices, beforeScaleServices, beforeRunServices, beforeAllowTraffic?

**Comment by mwkaufman** [comment]
Sounds like -> beforeLaunchServices, beforeTraffic per 7/10 noop group meeting.

**Comment by arbitrarytech** [comment]
This was implemented with the new lifecycle names `beforeStartingServices` and `beforeTraffic` in `noop-local@1.0.13`
f8b7e63ddce0aa875bedb2354be737c7f12fd9d9
